name: gamestore_frontend
description: Frontend Flutter para GameStore

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  file_picker: ^6.1.1
  path_provider: ^2.1.2
  provider: ^6.1.0
  intl: ^0.18.1
  confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/cover.png
